### PR TITLE
Add source build capabilities

### PR DESCRIPTION
**Pull request by mara004**

### CODE REVIEW

**Review by adam-huganir — APPROVED** [review]
All looks good to me to the extent that I understand it since I am not familiar with sourcebuild 👍

**Comment by adam-huganir** [comment]
merged 👍

**Comment by mara004** [comment]
While I've already built a lot of programs/libraries from source, PDFium has been particularly tough.
It uses kind of its own tooling and structure, so it's not really arranged for being easily buildable by non-Google people.

What troubles me with the source build is that downloading PDFium takes sooo long. Maybe I can pull in the depot tools patches from https://github.com/bblanchon/pdfium-binaries/pull/39, that might improve downloading time.

**Comment by mara004** [comment]
> Maybe I can pull in the depot tools patches from bblanchon/pdfium-binaries#39 - that might improve downloading time.

Done with 6e53a90d689aa9b55ec98e7d79adf7c2b6b33a96

**Pull request merged**
